### ISSUE TITLE
local distances return faulty output

### ISSUE THREAD

**Issue by sina-mansour** [the-virtual-brain/tvb-gdist#21]
Hi,

I'm using the `gdist.local_gdist_matrix` function to get the all to all local distances. There are two problems however that seem wrong with the output:

1. The output matrix is not symmetric. However, if a distance from `i` to `j` is reported, I don't see why the distance from `j` to `i` shouldn't be reported. Am I right to expect a symmetric matrix as an output?

2. Some of the elements of the output matrix are larger than the `max_distance` provided as an input. Is there something wrong going on in the code?

Thanks.

**Comment by liadomide** [comment]
@sina-mansour 
1. From our tests the symmetry is broken only with a small difference (<1e-6) due to precision issues. Have you observed something different ?
2. Indeed, the `max_distance` was not considered before. It should be now (after we will merge #38 from @ayan-b ). But we still consider acceptable if `max_distance` will be  overcome with a very small Epsilon
